### ISSUE TITLE
OrientJS 3.0: Error when using null params

### ISSUE THREAD

**Issue by big213** [orientechnologies/orientjs#335]
OrientJS Version: 3.0.0-beta3
OrientDB Version: 3.0.7

Steps to reproduce error:
`INSERT INTO V SET foo = null`
`session.query("SELECT FROM #1:0 WHERE foo = :foo", { params: { foo: null } })`

Results in this error:
`Unhandled rejection TypeError: err.isTokenException is not a function`

**Comment by wolf4ood** [comment]
Hi @big213 

i've just pushed a fix. It will be available on the next release

Thanks

**Comment by big213** [comment]
Hi @wolf4ood 

OrientDB 3.0.8 just rolled out recently, and it seems to be working well so far. However, null params as described in this issue are still not working. In fact, it doesn't throw any error anymore, the query just doesn't return. I guess it is not a huge isssue, I just switched the param to `''` for now, but any chance you could push the fix to npm so I can test it?

**Comment by wolf4ood** [comment]
Hi @big213 

i've published `orientjs-3.0.0` let me know if it is ok

Thanks

**Comment by big213** [comment]
@wolf4ood All good now, thanks!
