### ISSUE TITLE
.unwind not working

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientjs#367]
```
var r = session.select().from('TableA').unwind('Field')
console.log(r.toString())
```

returns : `SELECT * FROM TableA`

It ignores **unwind**. What is wrong with this please ?

**Comment by wolf4ood** [comment]
Hi @petervavro 

sorry for the late response, i will give it a look tomorrow

Thanks

**Comment by wolf4ood** [comment]
hi @petervavro 

i've just pushed a fix for this. It will be available in the next OrientJS release

Thanks

**Comment by wolf4ood** [comment]
Hi @petervavro 

i've just published on npm OrientJS 3.0.5 with this fix

Thanks

**Comment by petervavro** [comment]
I did upgrade to 3.0.5 but unfortunately, it still does not work.

**Comment by wolf4ood** [comment]
Hi @petervavro 

how is your code different from this test case?

https://github.com/orientechnologies/orientjs/blob/3.0.5/test/database/database-statement-test.js#L706

Thanks
