### ISSUE TITLE
Throwing error "Unsupported field type 95 for field undefined"

### ISSUE THREAD

**Issue by Nilesh-Kale-2212** [orientechnologies/orientjs#431]
We are using the OrientDB of version 3.0.29 and OrientJS of version 3.0.10.
When I am trying to get a record of the object available into the database, the database throwing an error that "**Unsupported field type 95 for field undefined**"

The logs are displaying as follows 
````
/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:161
      throw new Error(`Unsupported field type ${type} for field ${fieldName}`);
      ^
Error: Unsupported field type 95 for field undefined
    at parseValue (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:161:13)
    at parseEmbeddedMap (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:355:13)
    at parseValue (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:135:16)
    at parseEmbeddedMap (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:355:13)
    at parseValue (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:135:16)
    at parseFields (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:79:14)
    at parseElement (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:88:16)
    at deserializeProjection (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:41:16)
    at Object.deserialize (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/deserializer-binary.js:25:14)
    at child.<anonymous> (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:1034:34)
    at child.Operation.parseBytes (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:855:12)
    at child.Operation.consume (/usr/src/app/node_modules/orientjs/lib/client/network/protocol37/operation.js:571:35)
    at ONetworkConnection.Connection.process (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:462:17)
    at ONetworkConnection.Connection.handleSocketData (/usr/src/app/node_modules/orientjs/lib/client/network/conn.js:344:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
````

We have check our database scheme using the following query but into classes, we are not able to find the "type: 95" property anywhere.
````
select expand(classes) from metadata:schema LIMIT -1
````

Please help us to solve this obstacle.

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

this seems like a projection. Which kind of query did you use?

Were embededd object/map involved?

Are you able to identify the record which give this exception?

Thanks

**Comment by Nilesh-Kale-2212** [comment]
@wolf4ood 

Yes, there are some embedded objects in the projection. 
I am getting stuck because other objects with the same embedded values return the results but one object throwing an error if I am getting the result for that object. 

I will provide enough information about this issue as earlier.

Thanks

**Comment by wolf4ood** [comment]
@Nilesh-Kale-2212 

Thanks let me know. I was not able to reproduce this. 

IF you are able to provide a reproducer or a record that give this exception, i will fix it asap

Thanks

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

any luck with the reproducer?

Thanks

**Comment by Nilesh-Kale-2212** [comment]
@wolf4ood 
I apologized for waiting for you a long time.

Previously, I was using the database with version 3.0.1 and orient JS 3.0.1.
In that, I have created some objects with string and embedded map properties. Into that the embedded map I was storing the value of version changes of name

E.g.
Class Car with Properties Name (String), Version (String) and Versioning (Embedded Map)
When I update the name of the car then versioning maintains the previous name of the car.
In that, the record gets stored as following

When I create an object using orient JS the record created like
Name : "BMW-C", Version : 0.1, Versioning : null
When I update an object using orient JS then record created like
Name "BMW", Version : 0.2, Versioning { "0.1" : {"@type":"d", "Name": "BMW-C"}}

When I get the record of cars, then all results are received.

Later on, I have updated my Orient DB to 3.0.29 and Orient JS to 3.0.10 and used the same database.
And when I am trying to get records of cars then ti throwing the error as mentioned.

So I updated versioning information manually from the database to set
{ "0.1" : {"Name": "BMW-C"}}
and tried to get the results and results are received.
I don't have any idea how it worked.
Again I update the versioning property with
{ "0.1" : {"@type":"d", "Name": "BMW-C"}}
and tried to get records but end up with this error

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

let me check.

Thanks

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

which type is Versioning. Is i declared on the schema?

Thanks

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

good news. It should be fixed. I've just release 3.0.11 version of OrientJS. 

Could you please confirm that it's fixed?

Thanks

**Comment by Nilesh-Kale-2212** [comment]
@wolf4ood 

Thanks for the update.
I will test the resolution and let you know about this.

**Comment by Nilesh-Kale-2212** [comment]
@wolf4ood 

We have updated the orient JS version and checked for the resolution. But unfortunately, we found that the problem is not solved.

Versioning type is EMBEDDEDMAP.

Is this the problem of the database migration from 3.0.1 to 3.0.29.
Because the old database (3.0.9) have the object with versioning like 

````
{
    "0.1": {
        "@type": "d",
        "@version": 0,
        "Name": "BMW Classic"
    }
}

````

**Comment by wolf4ood** [comment]
Hi @Nilesh-Kale-2212 

with 3.0.11 right?

in case do you have a simple script SQL to reproduce this issue via nodejs?

It will help me to fix it quickly

Thanks

**Comment by VikramShityalkar** [comment]
Hi @wolf4ood,
We will create one sample and post here.
